version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cruddr-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cruddr-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FRONTEND_URL=*
      - BACKEND_URL=*
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
